<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class MenuBuilderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admin_menus = array(
            array(
                "id" => 1,
                "name" => "main_menu",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 2,
                "name" => "footer_menu_one",
                "created_at" => "2023-09-13 05:31:22",
                "updated_at" => "2023-09-13 05:31:22",
            ),
            array(
                "id" => 3,
                "name" => "footer_menu_two",
                "created_at" => "2023-09-13 05:34:53",
                "updated_at" => "2023-09-13 05:34:53",
            ),
            array(
                "id" => 4,
                "name" => "footer_menu_three",
                "created_at" => "2023-09-13 05:35:29",
                "updated_at" => "2023-09-13 05:35:29",
            ),
        );

        $admin_menu_items = array(
            array(
                "id" => 2,
                "label" => "Home",
                "link" => "/",
                "parent_id" => 0,
                "sort" => 2,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2023-09-13 06:00:59",
                "updated_at" => "2023-09-13 06:14:43",
            ),
            array(
                "id" => 3,
                "label" => "About",
                "link" => "/about",
                "parent_id" => 0,
                "sort" => 1,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2023-09-13 06:02:18",
                "updated_at" => "2023-09-13 06:16:10",
            ),
            array(
                "id" => 4,
                "label" => "Contact",
                "link" => "/contact",
                "parent_id" => 0,
                "sort" => 0,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2023-09-13 06:03:39",
                "updated_at" => "2023-09-13 06:16:10",
            ),
            array(
                "id" => 5,
                "label" => "Our Service",
                "link" => "#",
                "parent_id" => 0,
                "sort" => 3,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2023-09-13 06:04:12",
                "updated_at" => "2023-09-13 06:04:12",
            ),
            array(
                "id" => 6,
                "label" => "More About Us",
                "link" => "#",
                "parent_id" => 0,
                "sort" => 4,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2023-09-13 06:04:27",
                "updated_at" => "2023-09-13 06:04:27",
            ),
            array(
                "id" => 7,
                "label" => "Trams and Condition",
                "link" => "/trams-and-conditions",
                "parent_id" => 0,
                "sort" => 3,
                "class" => NULL,
                "menu_id" => 3,
                "depth" => 0,
                "created_at" => "2023-09-13 06:56:59",
                "updated_at" => "2023-09-13 07:00:59",
            ),
            array(
                "id" => 8,
                "label" => "Privacy Policy",
                "link" => "/privacy-policy",
                "parent_id" => 0,
                "sort" => 2,
                "class" => NULL,
                "menu_id" => 3,
                "depth" => 0,
                "created_at" => "2023-09-13 06:57:29",
                "updated_at" => "2023-09-13 07:00:59",
            ),
            array(
                "id" => 9,
                "label" => "More",
                "link" => "#",
                "parent_id" => 0,
                "sort" => 4,
                "class" => NULL,
                "menu_id" => 3,
                "depth" => 0,
                "created_at" => "2023-09-13 06:59:45",
                "updated_at" => "2023-09-13 07:00:59",
            ),
            array(
                "id" => 10,
                "label" => "Blogs",
                "link" => "/blogs",
                "parent_id" => 0,
                "sort" => 0,
                "class" => NULL,
                "menu_id" => 3,
                "depth" => 0,
                "created_at" => "2023-09-13 07:00:20",
                "updated_at" => "2023-09-13 07:00:56",
            ),
            array(
                "id" => 11,
                "label" => "Chefs",
                "link" => "/chefs",
                "parent_id" => 0,
                "sort" => 1,
                "class" => NULL,
                "menu_id" => 3,
                "depth" => 0,
                "created_at" => "2023-09-13 07:00:41",
                "updated_at" => "2023-09-13 07:01:05",
            ),
            array(
                "id" => 12,
                "label" => "Contact",
                "link" => "/contact",
                "parent_id" => 0,
                "sort" => 0,
                "class" => NULL,
                "menu_id" => 4,
                "depth" => 0,
                "created_at" => "2023-09-13 07:03:56",
                "updated_at" => "2023-09-13 07:04:12",
            ),
            array(
                "id" => 13,
                "label" => "About",
                "link" => "/about",
                "parent_id" => 0,
                "sort" => 1,
                "class" => NULL,
                "menu_id" => 4,
                "depth" => 0,
                "created_at" => "2023-09-13 07:04:11",
                "updated_at" => "2023-09-13 07:04:33",
            ),
            array(
                "id" => 14,
                "label" => "Blogs",
                "link" => "/bogs",
                "parent_id" => 0,
                "sort" => 3,
                "class" => NULL,
                "menu_id" => 4,
                "depth" => 0,
                "created_at" => "2023-09-13 07:04:33",
                "updated_at" => "2023-09-13 07:04:33",
            ),
            array(
                "id" => 15,
                "label" => "Home",
                "link" => "/",
                "parent_id" => 0,
                "sort" => 0,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2023-09-13 07:21:58",
                "updated_at" => "2023-09-13 07:22:21",
            ),
            array(
                "id" => 16,
                "label" => "About",
                "link" => "/about",
                "parent_id" => 0,
                "sort" => 1,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2023-09-13 07:22:20",
                "updated_at" => "2023-09-13 07:22:50",
            ),
            array(
                "id" => 17,
                "label" => "Chefs",
                "link" => "/chef",
                "parent_id" => 23,
                "sort" => 5,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 1,
                "created_at" => "2023-09-13 07:22:49",
                "updated_at" => "2023-09-13 07:40:11",
            ),
            array(
                "id" => 18,
                "label" => "Blogs",
                "link" => "/blogs",
                "parent_id" => 0,
                "sort" => 2,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2023-09-13 07:23:05",
                "updated_at" => "2023-09-13 09:09:04",
            ),
            array(
                "id" => 19,
                "label" => "Contact",
                "link" => "/contact",
                "parent_id" => 0,
                "sort" => 3,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2023-09-13 07:23:23",
                "updated_at" => "2023-09-13 07:27:29",
            ),
            array(
                "id" => 20,
                "label" => "Testimonials",
                "link" => "/testimonials",
                "parent_id" => 23,
                "sort" => 6,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 1,
                "created_at" => "2023-09-13 07:24:10",
                "updated_at" => "2023-09-13 07:27:35",
            ),
            array(
                "id" => 21,
                "label" => "Privacy Policy",
                "link" => "/privacy-policy",
                "parent_id" => 23,
                "sort" => 7,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 1,
                "created_at" => "2023-09-13 07:24:53",
                "updated_at" => "2023-09-13 07:27:17",
            ),
            array(
                "id" => 22,
                "label" => "Trams and Conditions",
                "link" => "/trams-and-conditions",
                "parent_id" => 23,
                "sort" => 8,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 1,
                "created_at" => "2023-09-13 07:25:15",
                "updated_at" => "2023-09-13 07:27:29",
            ),
            array(
                "id" => 23,
                "label" => "Pages",
                "link" => "#",
                "parent_id" => 0,
                "sort" => 4,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2023-09-13 07:26:58",
                "updated_at" => "2023-09-13 07:27:32",
            ),
            array(
                "id" => 24,
                "label" => "Products",
                "link" => "/products",
                "parent_id" => 0,
                "sort" => 1,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2023-09-13 07:26:58",
                "updated_at" => "2023-09-13 07:27:32",
            ),
        );

        DB::table('admin_menus')->insert($admin_menus);

        DB::table('admin_menu_items')->insert($admin_menu_items);

    }
}
